## FOR LATER, COMPARE WITH ORIGINAL. WHY DID I MAKE THIS? WAS IT GOOD



$Title = "Program List Generator" ; $host.UI.RawUI.WindowTitle = $Title
$list = ".\Program List.txt" ; $line = "`n`n==================================================`n`n"
$LogName = ".\$Env:COMPUTERNAME-$env:USERNAME.html"
If ($List){ Remove-Item $List }
If ($LogName){ Remove-Item $LogName }
Function Unview() {
    $UnviewApplication = ".\UninstallView.exe"
    $UnviewZipped = ".\uninstallview-x64.zip"
    $UnviewURL = "https://www.nirsoft.net/utils/uninstallview-x64.zip"
    
    If (!(Test-Path $UnviewApplication)){
        Write-Host "WARNING:" -NoNewline -ForegroundColor White -BackgroundColor RED ; Write-Host " UninstallView by NirSoft was not found.. Downloading Now.."
        Start-Bitstransfer -Source $UnviewURL -Destination $UnviewZipped -TransferType Download -Dynamic -Verbose | Out-Host
        If ($?){
            Expand-Archive -Path $UnviewZipped -DestinationPath ".\" -Force
            Remove-Item ".\readme.txt" -Force
            Remove-Item ".\UninstallView.chm" -Force
            Remove-Item $UnviewZipped -Force
        }
    }

    Write-Host "Running UninstallView by NirSoft"
    Start-Process "$UnviewApplication" -ArgumentList "/shtml $LogName" -Verbose
}
Unview
If (Test-Path $List){ Start-Transcript -Path $List -NoClobber -Append } else { Start-Transcript -Path $List }
Write-Host "Generating Program Lists $line"
$WingetPath = "$Env:USERPROFILE\AppData\Local\Microsoft\WindowsApps\winget.exe"
If (Test-Path $WingetPath){ Write-Host "Adding list of Winget Packages to $list"
winget list --accept-source-agreements | Out-Host
}
Write-Host "`n`nGenerating List of Installed AppxPackages"
(Get-AppxPackage -AllUsers).PackageFamilyName | Out-Host
Write-Host "`n`nFinishing Up..."
Stop-Transcript
Start-Sleep -Seconds 10
$Date = Get-Date
Send-MailMessage -From 'Program List Generator <newloads@shaw.ca>' -To '<newloadslogs@shaw.ca> , <newloads@shaw.ca>' -Subject "Program List Generation" -Attachments $List,$LogName -DeliveryNotification OnSuccess, OnFailure -SmtpServer 'smtp.shaw.ca' -Verbose -ErrorAction SilentlyContinue -Body "Emailed list of Programs Generated by Program List Generator.exe on $Date"
Write-Host "Exiting.."
Start-Sleep -Seconds 3
Exit
# SIG # Begin signature block
# MIIHAwYJKoZIhvcNAQcCoIIG9DCCBvACAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU2M5WY7hxwKM+IoHLutxx4cl9
# XYqgggQiMIIEHjCCAwagAwIBAgIQSGGcb8+NWotO0lk12RTDYTANBgkqhkiG9w0B
# AQsFADCBlDELMAkGA1UEBhMCQ0ExCzAJBgNVBAgMAkJDMREwDwYDVQQHDAhWaWN0
# b3JpYTEeMBwGCSqGSIb3DQEJARYPY2lyY2xvbEBzaGF3LmNhMR8wHQYJKoZIhvcN
# AQkBFhBuZXdsb2Fkc0BzaGF3LmNhMRAwDgYDVQQKDAdDaXJjbG9sMRIwEAYDVQQD
# DAlOZXcgTG9hZHMwHhcNMjMwNjIxMDMyMTQ3WhcNMjQwNjIxMDM0MTQ3WjCBlDEL
# MAkGA1UEBhMCQ0ExCzAJBgNVBAgMAkJDMREwDwYDVQQHDAhWaWN0b3JpYTEeMBwG
# CSqGSIb3DQEJARYPY2lyY2xvbEBzaGF3LmNhMR8wHQYJKoZIhvcNAQkBFhBuZXds
# b2Fkc0BzaGF3LmNhMRAwDgYDVQQKDAdDaXJjbG9sMRIwEAYDVQQDDAlOZXcgTG9h
# ZHMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDQt44ecXJMhStrhxP7
# iZBc+ud0YMIoM1ckjS9fAb1hwa8b79DWgMbTLoRx5fQG6Hiq4+1hzCaR9kAFgn8y
# gHkdrv21XbaATgY+KyNk+e0QryyRbjkUtvbO7ZUNkxm1ld3epvJqs4rPGPMpnoj+
# fzbs1YjzEoq1Pd0hfc032DUfmjcay6k5kgFFoCzbrjLQoP8cyneJ8WE7muwbZVUP
# cjA1UujXDeO6O2KMJtnPkCjr+8vlGfkxc6zfdWMxXn5yCFZjKIGwiLvSlXBlGTKp
# dayNTTz8TZC96mtQhVez3WZU9MzP/gicbzXwb6gzkNsJYYTiN+gI+MwqJnSbEPNY
# krRJAgMBAAGjajBoMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcD
# AzAiBgNVHREEGzAZghd3d3cubW90aGVyY29tcHV0ZXJzLmNvbTAdBgNVHQ4EFgQU
# JkPTOiVNkHT7I4KIkYbt1sJ26HMwDQYJKoZIhvcNAQELBQADggEBAIBa7suOeJ5L
# 20Eftw4YffTpYsZHlWBrhJOJWS/kye7LtSUMpusAhLK9kQpbtHclCo7VRIutXNip
# UlMF4pVLBi3LI7hNKPnw1j0PB/4hNwjHMwlcPGvY+wcFPZbJtpwiPNeiIpfA6n8U
# ph2Z3CmdeFOBdSzKYfo77ofOuyuYsnp+272wM6nOrQEsJoqp+TWjeGiKkLZFhXgO
# b6YyAcn+ZKDJzIMoNJ0DuzRUWY4ONdwA4qwvzlOn+PHYivCkvbZUtOc39Hvr7q/h
# 4y6ftOGq7K0MH002S4rkIfuhmKodXxLch1oCzJWE51s64nCfe808LSk7D8J0QbYN
# QMT1YZwc3boxggJLMIICRwIBATCBqTCBlDELMAkGA1UEBhMCQ0ExCzAJBgNVBAgM
# AkJDMREwDwYDVQQHDAhWaWN0b3JpYTEeMBwGCSqGSIb3DQEJARYPY2lyY2xvbEBz
# aGF3LmNhMR8wHQYJKoZIhvcNAQkBFhBuZXdsb2Fkc0BzaGF3LmNhMRAwDgYDVQQK
# DAdDaXJjbG9sMRIwEAYDVQQDDAlOZXcgTG9hZHMCEEhhnG/PjVqLTtJZNdkUw2Ew
# CQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcN
# AQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUw
# IwYJKoZIhvcNAQkEMRYEFMo76IGc4UDWW7TBya+NGNprYIeAMA0GCSqGSIb3DQEB
# AQUABIIBAEJYPHYoYs5NUcR/IF+YcMJc3u5A1QtZInEG2BrIf8h5BNgnOIpIEkBd
# 7G1cDD38BvZgfAJbc6O0Uh4LphYm0QyMOoPhJiVPF1Rbb/81Tg5u33Fzy7qe9cwg
# k3A44o3tQlJG7eJhR71kQ/AGPrc42333imVSLEsgalaLpQAg2Tg4+vAywbxt+6l4
# xSio6GiAPVv5XVkfHrGL7IElqQYQLHKq32LorJJkGZBQjjrJSF8H3oPjeIafdzjI
# pPbZfGwLoAMlaSQzqnxdU9SGgKLZlv+3at6JNXNwDkKHjqElH9hd0aq5Cv0WF2eb
# U9my73KvQW1STZMSxhBN06iuNNtcrCs=
# SIG # End signature block
